Source Code/booky/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/',user_views.register,name='register'),
    path('profile/',user_views.profile,name='profile'),
    path('profile/edit/',user_views.edit_profile,name='edit-profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('user/<str:username>/', user_views.UserDetailView, name="user_detail_view"),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Source Code/main/urls.py
from django.urls import path
from .views import HomePage, BookUploadView, BookDetailView, BookUpdateView, BookDeleteView

urlpatterns = [
    path('', HomePage.as_view(), name="home"),
    path('uploadBook/', BookUploadView.as_view(), name="upload_book"),
    path('<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book-update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book-delete'),
]

Source Code/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image, ImageOps
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(default="", max_length=20)

    def __str__(self):
        return self.name

class Book(models.Model):
    uploader = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    title = models.CharField(default="", max_length=40)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='Genre', null=True)
    cover = models.ImageField(upload_to='book_covers')
    no_of_pages = models.IntegerField()
    price = models.IntegerField()
    authors = models.CharField(default="", max_length=25)
    publications = models.CharField(default="", max_length=20)
    synopsis = models.TextField(default="")
    upload_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk': self.pk})


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.cover.path)

        # ImageOps compatible mode
        if image.mode not in ("L", "RGB"):
            image = image.convert("RGB")

        imagefit = ImageOps.fit(image, (200, 200), Image.ANTIALIAS)
        imagefit.save(self.cover.path)

    class Meta:
        ordering = ['-upload_date']

    def __str__(self):
        return self.title
    

Source Code/main/forms.py
from django import forms
from .models import Book

class BookUploadForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ['title', 'no_of_pages', 'price', 'authors', 'publications', 'genre', 'synopsis', 'cover']

Source Code/main/views.py
from .models import Book
from django.views import generic
from .forms import BookUploadForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect,get_object_or_404,HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django_filters.views import FilterView
from .filters import BookFilter
from django.contrib.auth.models import User


class HomePage(FilterView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'main/home.html'
    filterset_class = BookFilter # ADD YOUR filterset class
    paginate_by = 6


class BookUploadView(LoginRequiredMixin, CreateView):
    model = Book
    template_name = 'main/upload_book.html'
    fields = ['title', 'no_of_pages', 'price', 'authors', 'publications', 'genre', 'synopsis', 'cover']
    
    def form_valid(self, form):
        form.instance.uploader = self.request.user
        return super().form_valid(form)


class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = 'main/book_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        user = get_object_or_404(User, username=self.object.uploader)
        # Rating calculation
        if user.profile.total_seller_ratings > 0:
            seller_rating = round(user.profile.seller_rating/user.profile.total_seller_ratings)
        else:
            seller_rating = 0
        
        context['seller_rating'] = seller_rating
        print(self.object.uploader)
        return context


class BookUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Book
    template_name = 'main/upload_book.html'
    fields = ['title', 'no_of_pages', 'price', 'authors', 'publications', 'synopsis', 'cover']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        Book = self.get_object()
        if self.request.user == Book.uploader:
            return True
        return False


class BookDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Book
    template_name = 'main/book_confirm_delete.html'
    success_url = '/'
    def test_func(self):
        Book = self.get_object()
        if self.request.user == Book.uploader:
            return True
        return False


#class SearchResultsView(ListView):
#    model = Book
#    template_name = 'main/search_results.html'
#
#    def get_queryset(self):
#        query = self.request.GET.get('query')
#        object_list = Book.objects.filter(title__icontains=query)
#        return object_list
#
#    def get_context_data(self, **kwargs):
#        # Call the base implementation first to get a context
#        context = super(SearchResultsView, self).get_context_data(**kwargs)
#        # Add in additional context
#        context['query'] = self.request.GET.get('query')
#        return context

Source Code/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- font awesome -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

  <!-- Font links -->
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- main css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block css_link %}

  {% endblock %}

  {% if title %}
  <title>BOOKy - {{ title }}</title>
  {% else %}
  <title>BOOKy</title>
  {% endif %}
</head>

<body style="font-family: 'Raleway', sans-serif;">
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: black;">
    <a class="navbar-brand navLogo" href="{% url 'home' %}">BOOKy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
      </ul>
      <ul class="navbar-nav justify-content-end ">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'upload_book' %}" style="color: white;"><i class="fas fa-upload"></i> <span>Upload</span></a>
        </li>
        <ul class="navbar-nav justify-content-end pl-3">
        <li class="nav-item dropdown show">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="padding: 0;"><img style="height: 40px; width: 40px;" src="{{ request.user.profile.image.url }}" class="img-fluid rounded-circle mx-auto d-block" alt="profile pic"></a>
            <div class="dropdown-menu dropdown-menu-right" style="background-color: black;border: 1px solid #26262a; box-shadow: 0 6px 15px rgba(36, 37, 38, 0.5);">
                <a href="{% url 'profile' %}" class="dropdown-item leftNav">My profile</a>
                <!-- <a href="#" class="dropdown-item">Settings</a> -->
                <div class="dropdown-divider"></div>
                <a href="{% url 'logout' %}" class="dropdown-item leftNav">Logout</a>
            </div>
        </li>
        
      </ul>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}" style="padding: 0;"><img style="height: 50px; width: 50px;" src="{{ user.profile.image.url }}" class="img-fluid rounded-circle mx-auto d-block" alt="profile pic"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Log out</a>
        </li> -->
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  <!-- <br><h1 class="heading text-center bg-grey">Let's change the WORLD!</h1><br> -->
  {% block nonContainer %}
  {% endblock %}
  <div class="container">
    {% block content %}

    {% endblock %}
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

Source Code/main/templates/main/book_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html style="height: 100%;">
    <head>
        <!-- font awesome -->
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
      
        <!-- Font links -->
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
      
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      
        <!-- <link rel="stylesheet" href="{% static 'users/main.css' %}"> -->


        <title>Delete Book</title>
      </head>
<body style="font-family: 'Raleway', sans-serif;">
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Confirm Delete</h5>
                    <p class="card-text">Are you sure you want to delete the book "{{object.title}}"</p>
                    <form method="POST">
                        {%csrf_token%}
                        <a class="btn btn-secondary" href="{% url 'book-detail' object.id %}"><i class="fas fa-window-close"></i> Cancel</a>
                        <button class="btn btn-danger" type="submit"><i class="fas fa-trash-alt"></i> Yes, Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>

Source Code/main/templates/main/book_detail.html
{% extends "main/base.html" %}
{% load static %}
{% block css_link %}
<link rel="stylesheet" href="{% static 'users/main.css' %}">
<style>

    .checked{
            color: #FFAE02;
        }
    </style>
{% endblock %}

{% block content %}
<div class="card"
style="background-color: white; border-radius: .75rem; box-shadow: 0 6px 15px rgba(36, 37, 38, 0.5); margin-top: 100px;">
<div class="row no-gutters">
    <div class="col-md-2 px-4 py-4 text-center pt-5 pb-2">
        <img src="{{ object.cover.url }}" class="img-fluid mx-auto d-block" alt="">
    </div>
    <div class="col pt-4 pb-2">
        <div class="card-body px-4">
            <h2 class="card-title mb-0">{{ object.title }}</h2><small class="text-muted"><span>uploaded at {{ object.upload_date|date:"F d, Y" }}</span></small>
            <p class="card-text mt-1 mb-0 p-1">Author: {{ object.authors }}</p>
            <p class="card-text m-0 p-1">Genre: {{ object.genre }}</p>
            <p class="card-text m-0 p-1">Publication: {{ object.publications }}</p>
            <h3 class="card-text mt-5">৳ {{ object.price }}</h3>
        </div>
    </div>
    <div class="col" >
        <div class="card-body h-100" style="background-color: #F6F6F6;">
            <h3 class="card-title mb-0 pt-4 pb-3">Lender Info</h3>
            <a href="{% url 'user_detail_view' username=book.uploader.username %}"><p class="card-text mt-1 mb-0 p-2"><i class="fas fa-user"></i> {{ object.uploader }}</p></a>
            
            <div class="rating p-2" id="seller_rating">Rating:
                {% if seller_rating > 0 %}
                <!-- <span style="font-style: italic;"> -->
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                <!-- </span> -->
                
                {% else %}
                <span style="font-style: italic;">
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                    <span class="far fa-star"></span>
                </span>
                {% endif %}
            </div>
            <script>
                let seller_rating = {{ seller_rating }}

                let seller_ancestor = document.getElementById('seller_rating')
                let seller_descendents = seller_ancestor.getElementsByTagName('*');

                // coloring seller rating star
                for(let i = 0; i < seller_rating; i++){
                    element = seller_descendents[i]
                    // console.log(element)
                    element.setAttribute('class','fa fa-star checked')
                }

            </script>
            <p class="card-text m-0 p-2"><i class="fas fa-home"></i> {{ user.profile.address }}</p>
            <p class="card-text m-0 p-2"><i class="fas fa-phone"></i> {{ user.profile.contact_no|truncatechars:4 }}xxxxx</p>
            {% if book.uploader == user %}
            <div class="buttons mt-2"><a class="btn btn-secondary" href="{% url 'book-update' book.id %}" ><i class="fas fa-pencil-alt"></i> Edit Book</a>
                <a href="{% url 'book-delete' book.id %}" class="btn btn-danger" type="submit"><i class="fas fa-trash-alt"></i> Delete Book</a></div>
            {% endif %}
        </div>
    </div>
</div>
</div>

<div class="row mt-5">
    <div class="col">
        <h1 class="pb-2">Synopsis</h1>
        <p class="p-1" style="font-size: 15px; font-style: italic;">{{ object.synopsis }}</p>
    </div>
</div>


{% endblock content %}

Source Code/main/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}
{% block css_link %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'users/main.css' %}">
<style>

#id_genre{
    margin-left: 5px;
    background-color: transparent;
} 
#div_id_genre{
    color: black;
}
#id_title{
    background-color: transparent;
} 
#id_authors{
    background-color: transparent;
} 
</style>
{% endblock %}

{% block nonContainer %}
<div class="container-fit" style="color: white; background:linear-gradient(135deg, #46464b 0%,#212125 100%); border-color: linear-gradient(135deg, #46464b 0%,#212125 100%); border-radius: .075rem; box-shadow: 0 6px 15px rgba(36, 37, 38, 0.5);">
    <div class="row m-0">
        <div class="col">
            <div class="jumbotron" style="margin-right: 18%; margin-left: 18%; background: transparent;">
                <h1 class="display-4">Join<span style="color: #8D121C;"> BOOKy </span>today</h1>
                <p class="lead">To begin lending and borrowing books with our community of book readers.</p>
                <hr class="my-4 w-100">
                <p class="mt-5">Not sure what to read next? Explore through our search option whatever you're looking for.</p>
                <div class="row a">
                    <div class="col ">
                        <div class="card card-body text-center" style="background:linear-gradient(135deg, #fbfbfc 0%,#f6f7f9 100%); border-radius: .75rem; box-shadow: 0 6px 15px rgba(36, 37, 38, 0.5);">
                
                            <form method="get" class="form-inline justify-content-around">
                                {{ filter.form|crispy }}
                
                            <button class="btn btn-dark" type="submit">Search</button>
                          </form>
                
                        </div>
                    </div>
                    
                </div>
              </div>
        </div>
    </div>
</div>
{% endblock nonContainer%}
{% block content %}


<div class="card-deck mt-5">
    <div class="row">
        {% if object_list.count > 1 %}
        {% for book in object_list %}
        <div class="col-lg-4 col-md-4 col-sm-12 mb-5">
            <div class="card"
                style="background-color: white; border-radius: .75rem; box-shadow: 0 6px 15px rgba(36, 37, 38, 0.3);">
                <img class="card-img-top img-responsive" style="height:100%;width:100%;" src="{{ book.cover.url }}"
                    alt="book cover">
                <div class="card-body">
                    <a href="{% url 'book-detail' book.id %}"
                        style="text-decoration: none; font-size: 18px; font-weight: 600; color: black;"
                        class="card-title">{{ book.title }}</a><br>
                        <a href="{% url 'user_detail_view' username=book.uploader.username %}"><small class="text-muted" style="font-size: 12px;"><i class="fas fa-user"></i> <span>{{ book.uploader }}</span></small></a><br><br>
                    <p class="card-text" style="font-size: 12px;">{{book.synopsis|truncatechars:100}}</p>
                    <p class="card-text"><small class="text-muted">Borrow Fee: <span style="color: black; font-weight: 600; font-style: italic;">৳{{ book.price}}</span></small></p>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
            {% if object_list.count == 0 %}
            <h3>Sorry, your search returned no results. Please try again with different keywords.</h3>
            {% else %}
            {% for book in object_list %}
            <div class="col-7 mb-5">
                <div class="card"
                    style="background-color: white; border-radius: .75rem; box-shadow: 0 6px 15px rgba(36, 37, 38, 0.3);">
                    <img class="card-img-top img-responsive" style="height:100%;width:100%;" src="{{ book.cover.url }}"
                        alt="book cover">
                    <div class="card-body">
                        <a href="{% url 'book-detail' book.id %}"
                            style="text-decoration: none; font-size: 18px; font-weight: 600; color: black;"
                            class="card-title">{{ book.title }}</a><br>
                            <a href="{% url 'user_detail_view' username=book.uploader.username %}"><small class="text-muted" style="font-size: 12px;"><i class="fas fa-user"></i> <span>{{ book.uploader }}</span></small></a><br><br>
                        <p class="card-text" style="font-size: 12px;">{{book.synopsis|truncatechars:100}}</p>
                        <p class="card-text"><small class="text-muted">Borrow Fee: <span style="color: black; font-weight: 600; font-style: italic;">৳{{ book.price}}</span></small></p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="row justify-content-center text-center">
        <div class="col-12">{% if is_paginated %}

            {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}

            {% if num == page_obj.number %}

            <a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>

            {% elif num < page_obj.number|add:'3' and num > page_obj.number|add:'-3' %}

                <a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>

                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}

                {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

Source Code/main/templates/main/search_results.html
<!-- {% extends "main/base.html" %}
{% load static %}
{% block css_link %}
<link rel="stylesheet" href="{% static 'users/main.css' %}">
{% endblock %}

{% block content %}

<br>
<div class="row">
	<div class="col">
		<div class="card card-body">

			<form method="get">
				{{filter.form}}

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>

		</div>
	</div>
	
</div>
<br>

{% for book in object_list %}
<div class="col-4 mb-5">
    <div class="card">
        <img class="card-img-top img-responsive" style="height:100%;width:100%;" src="{{ book.cover.url }}" alt="book cover">
        <div class="card-body">
            <a href="{% url 'book-detail' book.id %}" style="text-decoration: none; font-size: 22px; font-weight: 600; color: black;" class="card-title">{{ book.title }}</a><br>
            <small class="text-muted"><i class="fas fa-user"></i> <span>{{ book.uploader }}</span></small><br><br>
            <p class="card-text">{{book.synopsis|truncatechars:100}}</p>
            <p class="card-text"><small class="text-muted">Borrow Fee: <span style="color: black; font-weight: 600; font-style: italic;">৳{{ book.price }}</span></small></p>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<div class="container"><h2 class="mt-5">Sorry "{{query}}" Not Found...</h2></div>
{% endif %}

{% endblock content %} -->

Source Code/main/templates/main/upload_book.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block css_link %}
<link rel="stylesheet" href="{% static 'users/main.css' %}">
{% endblock %}

{% block content %}
<div class="container p-3">
    <div class="heading"><h1>Upload Your Book</h1></div>
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4", style="font-size: 18px;">Fill out all the information</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Upload</button>
        </div>
    </form>
</div>
</div>
{% endblock content %}